language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mPB/IdBnZ6KWDbsLove+l78nzqjt0PScV4vThFtupVeYQdxYThIDuqqclEA15uWQix+vOJu6C7bOUPUf+itQnapmULODBTaNgHl6Cg0qN/rRmDCwCSQJJpKh8abPexVZnzUSS2jdkMVgwaMIxB4SLPXtJtCQpjH6f3jWR83oLsfBrn//eH2a0+y9T2e26nR2jzKltIRjvC8gkA0x7eT0PnKTo+FOlY+knWqyepj0E8ssoNbIi06o+0lXSF+R/bmJhMcRzvDIJxuEG2zvuEp2yGjhO6MB9PtdKRFJgqpIAYrSaU7CFKJb9YRAJUVUwmQsFVP938ttdX354bpT2KmikdW4lkU7DLaQb4eTpq9gVH1Ox2EYXp0TA+uBjiXvFmt455WadMhLET+v4pkM1rafjL+bjPiMJZ/Dxyrc6C5pbovEiysM+IBrH72h9aJ0Ix7Ek59hxsWdZ5SDpjcQOk4708uxTKZ36pAjuFQjkNlFJ3oM0MfKqjF1O84PkaB7GjyQ21Fbz2u+zNw8GnwhPGqmY4JDFEpDkHta4oXCfEpwhyUGZ/QR4vxJ/m4G37zCH/XPA89JmX18j9pjEmtBS741Z41xDjgYWzZ+0p3zwzwSEO+5VhcUuMNZsWoh8sky0GD2IYEi08JlkMkqdjvTOU2BW4/C7xuwgdVj8MCYk0X1Mvk=
  app: vehicle-tracker-server
